

<Login>:

    email: email
    password: password


    FloatLayout:
        size: root.width, root.height
        Label:
            size_hint: 0.2, 0.05
            pos_hint: {'x':0.4, 'y':0.7}
            text: 'Email: '

        TextInput:
            size_hint: 0.4, 0.05
            pos_hint: {'x':0.3, 'y':0.6}
            id: email
            multiline: False

        Label:
            size_hint: 0.2, 0.05
            pos_hint: {'x':0.4, 'y':0.5}
            text: 'Password: '

        TextInput:
            size_hint: 0.4 , 0.05
            pos_hint: {'x':0.3, 'y':0.4}
            id: password
            multiline: False
        Button:
            size_hint: 0.3, 0.1
            pos_hint: {'x':0.2, 'y':0.2}
            text: 'Submit'
            on_press: root.submitButton()
        Button:
            size_hint: 0.3, 0.1
            pos_hint: {'x':0.5, 'y':0.2}
            text: 'Already have an account? Sign in here'
            on_press: root.toSignInButton()

<SignIn>:

    email: email
    password: password

    FloatLayout:
        size: root.width, root.height
        Label:
            size_hint: 0.2, 0.05
            pos_hint: {'x':0.4, 'y':0.7}
            text: 'Email: '

        TextInput:
            size_hint: 0.4, 0.05
            pos_hint: {'x':0.3, 'y':0.6}
            id: email
            multiline: False

        Label:
            size_hint: 0.2, 0.05
            pos_hint: {'x':0.4, 'y':0.5}
            text: 'Password: '

        TextInput:
            size_hint: 0.4 , 0.05
            pos_hint: {'x':0.3, 'y':0.4}
            id: password
            multiline: False
        Button:
            size_hint: 0.3, 0.1
            pos_hint: {'x':0.2, 'y':0.2}
            text: 'Sign In'
            on_press: root.signInButton()
        Button:
            size_hint: 0.3, 0.1
            pos_hint: {'x':0.5, 'y':0.2}
            text: 'back to login'
            on_press:
                root.manager.transition.direction = 'right'
                root.toLogin()



<Home>:
    GridLayout:
        cols:1
        id: title
        Label:
            text: 'Leaderboard'

        GridLayout:
            id: leaderboard
            cols: 3

        GridLayout:
            id: userstats
            cols: 3